const prisma = require("../../src/config/database");

async function insertMunicipios() {
  const municipios = [
    // ATLÁNTIDA (1)
    { nombre: "La Ceiba", id_departamento: 1 },
    { nombre: "El Porvenir", id_departamento: 1 },
    { nombre: "Tela", id_departamento: 1 },
    { nombre: "Jutiapa", id_departamento: 1 },
    { nombre: "La Masica", id_departamento: 1 },
    { nombre: "San Francisco", id_departamento: 1 },
    { nombre: "Arizona", id_departamento: 1 },
    { nombre: "Esparta", id_departamento: 1 },

    // CHOLUTECA (2)
    { nombre: "Choluteca", id_departamento: 2 },
    { nombre: "Apacilagua", id_departamento: 2 },
    { nombre: "Concepción de María", id_departamento: 2 },
    { nombre: "Duyure", id_departamento: 2 },
    { nombre: "El Corpus", id_departamento: 2 },
    { nombre: "El Triunfo", id_departamento: 2 },
    { nombre: "Marcovia", id_departamento: 2 },
    { nombre: "Morolica", id_departamento: 2 },
    { nombre: "Namasigüe", id_departamento: 2 },
    { nombre: "Orocuina", id_departamento: 2 },
    { nombre: "Pespire", id_departamento: 2 },
    { nombre: "San Antonio de Flores", id_departamento: 2 },
    { nombre: "San Isidro", id_departamento: 2 },
    { nombre: "San José", id_departamento: 2 },
    { nombre: "San Marcos de Colón", id_departamento: 2 },
    { nombre: "Santa Ana de Yusguare", id_departamento: 2 },

    // COLÓN (3)
    { nombre: "Trujillo", id_departamento: 3 },
    { nombre: "Balfate", id_departamento: 3 },
    { nombre: "Iriona", id_departamento: 3 },
    { nombre: "Limón", id_departamento: 3 },
    { nombre: "Sabá", id_departamento: 3 },
    { nombre: "Santa Fe", id_departamento: 3 },
    { nombre: "Santa Rosa de Aguán", id_departamento: 3 },
    { nombre: "Sonaguera", id_departamento: 3 },
    { nombre: "Tocoa", id_departamento: 3 },
    { nombre: "Bonito Oriental", id_departamento: 3 },

    // COMAYAGUA (4)
    { nombre: "Comayagua", id_departamento: 4 },
    { nombre: "Ajuterique", id_departamento: 4 },
    { nombre: "El Rosario", id_departamento: 4 },
    { nombre: "Esquías", id_departamento: 4 },
    { nombre: "Humuya", id_departamento: 4 },
    { nombre: "La Libertad", id_departamento: 4 },
    { nombre: "Lamaní", id_departamento: 4 },
    { nombre: "La Trinidad", id_departamento: 4 },
    { nombre: "Lejamaní", id_departamento: 4 },
    { nombre: "Meámbar", id_departamento: 4 },
    { nombre: "Minas de Oro", id_departamento: 4 },
    { nombre: "Ojos de Agua", id_departamento: 4 },
    { nombre: "San Jerónimo", id_departamento: 4 },
    { nombre: "San José de Comayagua", id_departamento: 4 },
    { nombre: "San José del Potrero", id_departamento: 4 },
    { nombre: "San Luis", id_departamento: 4 },
    { nombre: "San Sebastián", id_departamento: 4 },
    { nombre: "Siguatepeque", id_departamento: 4 },
    { nombre: "Villa de San Antonio", id_departamento: 4 },
    { nombre: "Las Lajas", id_departamento: 4 },
    { nombre: "Taulabé", id_departamento: 4 },

    // COPAN (5)
    { nombre: "Santa Rosa de Copán", id_departamento: 5 },
    { nombre: "Cabañas", id_departamento: 5 },
    { nombre: "Concepción", id_departamento: 5 },
    { nombre: "Copan Ruinas", id_departamento: 5 },
    { nombre: "Corquín", id_departamento: 5 },
    { nombre: "Cucuyagua", id_departamento: 5 },
    { nombre: "Dolores", id_departamento: 5 },
    { nombre: "Dulce Nombre", id_departamento: 5 },
    { nombre: "El Paraíso", id_departamento: 5 },
    { nombre: "Florida", id_departamento: 5 },
    { nombre: "La Jigua", id_departamento: 5 },
    { nombre: "La Unión", id_departamento: 5 },
    { nombre: "Nueva Arcadia", id_departamento: 5 },
    { nombre: "San Agustín", id_departamento: 5 },
    { nombre: "San Antonio", id_departamento: 5 },
    { nombre: "San Jerónimo", id_departamento: 5 },
    { nombre: "San José", id_departamento: 5 },
    { nombre: "San Juan de Opoa", id_departamento: 5 },
    { nombre: "San Nicolás", id_departamento: 5 },
    { nombre: "San Pedro", id_departamento: 5 },
    { nombre: "Santa rita", id_departamento: 5 },
    { nombre: "Trinidad de Copán", id_departamento: 5 },
    { nombre: "Veracruz", id_departamento: 5 },
    // CORTÉS (6)
    { nombre: "San Pedro Sula", id_departamento: 6 },
    { nombre: "Choloma", id_departamento: 6 },
    { nombre: "Omoa", id_departamento: 6 },
    { nombre: "Pimienta", id_departamento: 6 },
    { nombre: "Potrerillos", id_departamento: 6 },
    { nombre: "Puerto Cortés", id_departamento: 6 },
    { nombre: "San Antonio de Cortés", id_departamento: 6 },
    { nombre: "San Francisco de Yojoa", id_departamento: 6 },
    { nombre: "San Manuel", id_departamento: 6 },
    { nombre: "Santa Cruz de Yojoa", id_departamento: 6 },
    { nombre: "Villanueva", id_departamento: 6 },
    { nombre: "La Lima", id_departamento: 6 },

    // EL PARAÍSO (7)
    { nombre: "Yuscarán", id_departamento: 7 },
    { nombre: "Alauca", id_departamento: 7 },
    { nombre: "Danlí", id_departamento: 7 },
    { nombre: "El Paraíso", id_departamento: 7 },
    { nombre: "Güinope", id_departamento: 7 },
    { nombre: "Jacaleapa", id_departamento: 7 },
    { nombre: "Liure", id_departamento: 7 },
    { nombre: "Morocelí", id_departamento: 7 },
    { nombre: "Oropolí", id_departamento: 7 },
    { nombre: "Potrerillos", id_departamento: 7 },
    { nombre: "San Antonio de Flores", id_departamento: 7 },
    { nombre: "San Lucas", id_departamento: 7 },
    { nombre: "San Matías", id_departamento: 7 },
    { nombre: "Soledad", id_departamento: 7 },
    { nombre: "Teupasenti", id_departamento: 7 },
    { nombre: "Texiguat", id_departamento: 7 },
    { nombre: "Vado Ancho", id_departamento: 7 },
    { nombre: "Yauyupe", id_departamento: 7 },
    { nombre: "Trojes", id_departamento: 7 },

    // FRANCISCO MORAZÁN (8)
    { nombre: "Tegucigalpa", id_departamento: 8 },
    { nombre: "Alubarén", id_departamento: 8 },
    { nombre: "Cedros", id_departamento: 8 },
    { nombre: "Curarén", id_departamento: 8 },
    { nombre: "El Porvenir", id_departamento: 8 },
    { nombre: "Guaimaca", id_departamento: 8 },
    { nombre: "La Libertad", id_departamento: 8 },
    { nombre: "La Venta", id_departamento: 8 },
    { nombre: "Lepaterique", id_departamento: 8 },
    { nombre: "Maraita", id_departamento: 8 },
    { nombre: "Marale", id_departamento: 8 },
    { nombre: "Nueva Armenia", id_departamento: 8 },
    { nombre: "Ojojona", id_departamento: 8 },
    { nombre: "Orica", id_departamento: 8 },
    { nombre: "Reitoca", id_departamento: 8 },
    { nombre: "Sabanagrande", id_departamento: 8 },
    { nombre: "San Antonio de Oriente", id_departamento: 8 },
    { nombre: "San Buenaventura", id_departamento: 8 },
    { nombre: "San Ignacio", id_departamento: 8 },
    { nombre: "Cantarranas", id_departamento: 8 },
    { nombre: "San Miguelito", id_departamento: 8 },
    { nombre: "Santa Ana", id_departamento: 8 },
    { nombre: "Santa Lucía", id_departamento: 8 },
    { nombre: "Talanga", id_departamento: 8 },
    { nombre: "Tatumbla", id_departamento: 8 },
    { nombre: "Valle de Ángeles", id_departamento: 8 },
    { nombre: "Villa de San Francisco", id_departamento: 8 },
    { nombre: "Vallecillo", id_departamento: 8 },

    // GRACIAS A DIOS (9)
    { nombre: "Puerto Lempira", id_departamento: 9 },
    { nombre: "Brus Laguna", id_departamento: 9 },
    { nombre: "Ahuas", id_departamento: 9 },
    { nombre: "Juan Francisco Bulnes", id_departamento: 9 },
    { nombre: "Villeda Morales", id_departamento: 9 },
    { nombre: "Wampusirpe", id_departamento: 9 },

    // INTIBUCÁ (10)
    { nombre: "La Esperanza", id_departamento: 10 },
    { nombre: "Camasca", id_departamento: 10 },
    { nombre: "Colomoncagua", id_departamento: 10 },
    { nombre: "Concepción", id_departamento: 10 },
    { nombre: "Dolores", id_departamento: 10 },
    { nombre: "Intibucá", id_departamento: 10 },
    { nombre: "Jesús de Otoro", id_departamento: 10 },
    { nombre: "Magdalena", id_departamento: 10 },
    { nombre: "Masaguara", id_departamento: 10 },
    { nombre: "San Antonio", id_departamento: 10 },
    { nombre: "San Isidro", id_departamento: 10 },
    { nombre: "San Juan", id_departamento: 10 },
    { nombre: "San Marcos de la Sierra", id_departamento: 10 },
    { nombre: "San Miguel Guancapla", id_departamento: 10 },
    { nombre: "Santa Lucía", id_departamento: 10 },
    { nombre: "Yamaranguila", id_departamento: 10 },
    { nombre: "San Francisco de Opalaca", id_departamento: 10 },

    // ISLAS DE LA BAHÍA (11)
    { nombre: "Roatán", id_departamento: 11 },
    { nombre: "Guanaja", id_departamento: 11 },
    { nombre: "José Santos Guardiola", id_departamento: 11 },
    { nombre: "Utila", id_departamento: 11 },

    // LA PAZ (12)
    { nombre: "La Paz", id_departamento: 12 },
    { nombre: "Aguanqueterique", id_departamento: 12 },
    { nombre: "Cabañas", id_departamento: 12 },
    { nombre: "Cane", id_departamento: 12 },
    { nombre: "Chinacla", id_departamento: 12 },
    { nombre: "Guajiquiro", id_departamento: 12 },
    { nombre: "Lauterique", id_departamento: 12 },
    { nombre: "Marcala", id_departamento: 12 },
    { nombre: "Mercedes de Oriente", id_departamento: 12 },
    { nombre: "Opatoro", id_departamento: 12 },
    { nombre: "San Antonio del Norte", id_departamento: 12 },
    { nombre: "San José", id_departamento: 12 },
    { nombre: "San Juan", id_departamento: 12 },
    { nombre: "San Pedro de Tutule", id_departamento: 12 },
    { nombre: "Santa Ana", id_departamento: 12 },
    { nombre: "Santa Elena", id_departamento: 12 },
    { nombre: "Santa María", id_departamento: 12 },
    { nombre: "Santiago de Puringla", id_departamento: 12 },
    { nombre: "Yarula", id_departamento: 12 },

    // LEMPIRA (13)
    { nombre: "Gracias", id_departamento: 13 },
    { nombre: "Belén", id_departamento: 13 },
    { nombre: "Candelaria", id_departamento: 13 },
    { nombre: "Cololaca", id_departamento: 13 },
    { nombre: "Erandique", id_departamento: 13 },
    { nombre: "Gualcince", id_departamento: 13 },
    { nombre: "Guarita", id_departamento: 13 },
    { nombre: "La Campa", id_departamento: 13 },
    { nombre: "La Iguala", id_departamento: 13 },
    { nombre: "Las Flores", id_departamento: 13 },
    { nombre: "La Unión", id_departamento: 13 },
    { nombre: "La Virtud", id_departamento: 13 },
    { nombre: "Lepaera", id_departamento: 13 },
    { nombre: "Mapulaca", id_departamento: 13 },
    { nombre: "Piraera", id_departamento: 13 },
    { nombre: "San Andrés", id_departamento: 13 },
    { nombre: "San Francisco", id_departamento: 13 },
    { nombre: "San Juan Guarita", id_departamento: 13 },
    { nombre: "San Manuel Colohete", id_departamento: 13 },
    { nombre: "San Rafael", id_departamento: 13 },
    { nombre: "San Sebastián", id_departamento: 13 },
    { nombre: "Santa Cruz", id_departamento: 13 },
    { nombre: "Talgua", id_departamento: 13 },
    { nombre: "Tambla", id_departamento: 13 },
    { nombre: "Tomalá", id_departamento: 13 },
    { nombre: "Valladolid", id_departamento: 13 },
    { nombre: "Virginia", id_departamento: 13 },
    { nombre: "San Marcos de Caiquín", id_departamento: 13 },

    // OCOTEPEQUE (14)
    { nombre: "Ocotepeque", id_departamento: 14 },
    { nombre: "Belén Gualcho", id_departamento: 14 },
    { nombre: "Concepción", id_departamento: 14 },
    { nombre: "Dolores Merendón", id_departamento: 14 },
    { nombre: "Fraternidad", id_departamento: 14 },
    { nombre: "La Encarnación", id_departamento: 14 },
    { nombre: "La Labor", id_departamento: 14 },
    { nombre: "Lucerna", id_departamento: 14 },
    { nombre: "Mercedes", id_departamento: 14 },
    { nombre: "San Fernando", id_departamento: 14 },
    { nombre: "San Francisco del Valle", id_departamento: 14 },
    { nombre: "San Jorge", id_departamento: 14 },
    { nombre: "San Marcos", id_departamento: 14 },
    { nombre: "Santa Fe", id_departamento: 14 },
    { nombre: "Sensenti", id_departamento: 14 },
    { nombre: "Sinuapa", id_departamento: 14 },

    // OLANCHO (15)
    { nombre: "Juticalpa", id_departamento: 15 },
    { nombre: "Campamento", id_departamento: 15 },
    { nombre: "Catacamas", id_departamento: 15 },
    { nombre: "Concordia", id_departamento: 15 },
    { nombre: "Dulce Nombre de Culmí", id_departamento: 15 },
    { nombre: "El Rosario", id_departamento: 15 },
    { nombre: "Esquipulas del Norte", id_departamento: 15 },
    { nombre: "Gualaco", id_departamento: 15 },
    { nombre: "Guarizama", id_departamento: 15 },
    { nombre: "Guata", id_departamento: 15 },
    { nombre: "Guayape", id_departamento: 15 },
    { nombre: "Jano", id_departamento: 15 },
    { nombre: "La Unión", id_departamento: 15 },
    { nombre: "Mangulile", id_departamento: 15 },
    { nombre: "Manto", id_departamento: 15 },
    { nombre: "Salamá", id_departamento: 15 },
    { nombre: "San Esteban", id_departamento: 15 },
    { nombre: "San Francisco de Becerra", id_departamento: 15 },
    { nombre: "San Francisco de la Paz", id_departamento: 15 },
    { nombre: "Santa María del Real", id_departamento: 15 },
    { nombre: "Silca", id_departamento: 15 },
    { nombre: "Yocón", id_departamento: 15 },
    { nombre: "Patuca", id_departamento: 15 },

    // SANTA BÁRBARA (16)
    { nombre: "Santa Bárbara", id_departamento: 16 },
    { nombre: "Arada", id_departamento: 16 },
    { nombre: "Atima", id_departamento: 16 },
    { nombre: "Azacualpa", id_departamento: 16 },
    { nombre: "Ceguaca", id_departamento: 16 },
    { nombre: "Concepción del Norte", id_departamento: 16 },
    { nombre: "Concepción del Sur", id_departamento: 16 },
    { nombre: "Chinda", id_departamento: 16 },
    { nombre: "El Níspero", id_departamento: 16 },
    { nombre: "Gualala", id_departamento: 16 },
    { nombre: "Ilama", id_departamento: 16 },
    { nombre: "Las Vegas", id_departamento: 16 },
    { nombre: "Macuelizo", id_departamento: 16 },
    { nombre: "Naranjito", id_departamento: 16 },
    { nombre: "Nuevo Celilac", id_departamento: 16 },
    { nombre: "Nueva Frontera", id_departamento: 16 },
    { nombre: "Petoa", id_departamento: 16 },
    { nombre: "Protección", id_departamento: 16 },
    { nombre: "Quimistán", id_departamento: 16 },
    { nombre: "San Francisco de Ojuera", id_departamento: 16 },
    { nombre: "San José de las Colinas", id_departamento: 16 },
    { nombre: "San Luis", id_departamento: 16 },
    { nombre: "San Marcos", id_departamento: 16 },
    { nombre: "San Nicolás", id_departamento: 16 },
    { nombre: "San Pedro Zacapa", id_departamento: 16 },
    { nombre: "San Vicente Centenario", id_departamento: 16 },
    { nombre: "Santa Rita", id_departamento: 16 },
    { nombre: "Trinidad", id_departamento: 16 },

    // VALLE (17)
    { nombre: "Nacaome", id_departamento: 17 },
    { nombre: "Alianza", id_departamento: 17 },
    { nombre: "Amapala", id_departamento: 17 },
    { nombre: "Aramecina", id_departamento: 17 },
    { nombre: "Caridad", id_departamento: 17 },
    { nombre: "Goascorán", id_departamento: 17 },
    { nombre: "Langue", id_departamento: 17 },
    { nombre: "San Francisco de Coray", id_departamento: 17 },
    { nombre: "San Lorenzo", id_departamento: 17 },

    // YORO (18)
    { nombre: "Yoro", id_departamento: 18 },
    { nombre: "Arenal", id_departamento: 18 },
    { nombre: "El Negrito", id_departamento: 18 },
    { nombre: "El Progreso", id_departamento: 18 },
    { nombre: "Jocón", id_departamento: 18 },
    { nombre: "Morazán", id_departamento: 18 },
    { nombre: "Olanchito", id_departamento: 18 },
    { nombre: "Santa Rita", id_departamento: 18 },
    { nombre: "Sulaco", id_departamento: 18 },
    { nombre: "Victoria", id_departamento: 18 },
    { nombre: "Yorito", id_departamento: 18 },
  ];

  for (const municipio of municipios) {
    await prisma.municipio.create({
      data: municipio,
    });
  }

  console.log("Municipios insertados correctamente");
}

module.exports = { insertMunicipios };
