const prisma = require("../../src/config/database");

async function insertProductos() {
  const productos = [
    {
      nombre: "Llanta Michelin 205/55R16",
      lonas: 4,
      rin: 16,
      ancho_rin: 205,
      alto_rin: 55,
      version: "Primacy 4",
      profundidad: 8,
      indice_de_carga: 91,
      presion_maxima: 44,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 2500.0,
      precio_mayoreo: 2300.0,
      precio_coste: 1800.0,
      descripcion: "Llanta radial para turismo de alto rendimiento",
      id_marca: 1,
      id_categoria: 1,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Bridgestone 215/60R16",
      lonas: 4,
      rin: 16,
      ancho_rin: 215,
      alto_rin: 60,
      version: "Turanza T005",
      profundidad: 9,
      indice_de_carga: 95,
      presion_maxima: 46,
      indice_velocidad: 220,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 2800.0,
      precio_mayoreo: 2550.0,
      precio_coste: 2000.0,
      descripcion: "Llanta confiable para uso diario y carretera",
      id_marca: 2,
      id_categoria: 1,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Goodyear 265/65R17",
      lonas: 6,
      rin: 17,
      ancho_rin: 245,
      alto_rin: 75,
      version: "Wrangler All Terrain Adventure",
      profundidad: 10,
      indice_de_carga: 112,
      presion_maxima: 50,
      indice_velocidad: 180,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 4200.0,
      precio_mayoreo: 3900.0,
      precio_coste: 3200.0,
      descripcion: "Llanta para camioneta con excelente tracción",
      id_marca: 3,
      id_categoria: 2,
      id_diseno: 4,
    },
    {
      nombre: "Llanta Michelin 195/65R15",
      lonas: 4,
      rin: 15,
      ancho_rin: 245,
      alto_rin: 75,
      version: "Energy XM2+",
      profundidad: 8,
      indice_de_carga: 89,
      presion_maxima: 42,
      indice_velocidad: 190,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 2000.0,
      precio_mayoreo: 1850.0,
      precio_coste: 1500.0,
      descripcion: "Llanta económica para vehículo sedán",
      id_marca: 1,
      id_categoria: 1,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Bridgestone 245/75R16",
      lonas: 6,
      rin: 16,
      ancho_rin: 245,
      alto_rin: 75,
      version: "Dueler A/T 697",
      profundidad: 11,
      indice_de_carga: 109,
      presion_maxima: 52,
      indice_velocidad: 170,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 1500.0,
      precio_mayoreo: 1400.0,
      precio_coste: 1100.0,
      descripcion: "Llanta resistente para carga y trabajo",
      id_marca: 2,
      id_categoria: 3,
      id_diseno: 4,
    },
    {
      nombre: "Llanta Goodyear 225/60R17",
      lonas: 4,
      rin: 17,
      ancho_rin: 225,
      alto_rin: 60,
      version: "Assurance WeatherReady",
      profundidad: 9,
      indice_de_carga: 99,
      presion_maxima: 44,
      indice_velocidad: 200,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 3100.0,
      precio_mayoreo: 2900.0,
      precio_coste: 2200.0,
      descripcion: "Llanta todo tiempo para SUV mediano",
      id_marca: 3,
      id_categoria: 2,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Michelin 235/55R18",
      lonas: 6,
      rin: 18,
      ancho_rin: 235,
      alto_rin: 55,
      version: "Pilot Sport 4 SUV",
      profundidad: 10,
      indice_de_carga: 99,
      presion_maxima: 50,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 4800.0,
      precio_mayoreo: 4500.0,
      precio_coste: 3500.0,
      descripcion: "Alto rendimiento y confort para SUV",
      id_marca: 1,
      id_categoria: 2,
      id_diseno: 6,
    },
    {
      nombre: "Llanta Bridgestone 205/55R16",
      lonas: 4,
      rin: 16,
      ancho_rin: 205,
      alto_rin: 55,
      version: "Ecopia EP300",
      profundidad: 8,
      indice_de_carga: 91,
      presion_maxima: 44,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 2600.0,
      precio_mayoreo: 2400.0,
      precio_coste: 1900.0,
      descripcion: "Alternativa económica para turismo",
      id_marca: 2,
      id_categoria: 1,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Goodyear 195/65R15",
      lonas: 4,
      rin: 15,
      ancho_rin: 195,
      alto_rin: 65,
      version: "EfficientGrip Performance",
      profundidad: 8,
      indice_de_carga: 91,
      presion_maxima: 44,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 1850.0,
      precio_mayoreo: 1700.0,
      precio_coste: 1400.0,
      descripcion: "Ideal para compactos y sedanes",
      id_marca: 3,
      id_categoria: 1,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Michelin 265/70R17",
      lonas: 6,
      rin: 17,
      ancho_rin: 265,
      alto_rin: 70,
      version: "LTX A/T2",
      profundidad: 11,
      indice_de_carga: 112,
      presion_maxima: 50,
      indice_velocidad: 180,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 5500.0,
      precio_mayoreo: 5100.0,
      precio_coste: 4000.0,
      descripcion: "Llanta todo terreno para pickup y 4x4",
      id_marca: 1,
      id_categoria: 2,
      id_diseno: 4,
    },
    {
      nombre: "Llanta Continental 185/65R14",
      lonas: 4,
      rin: 14,
      ancho_rin: 185,
      alto_rin: 65,
      version: "ContiEcoContact 5",
      profundidad: 8,
      indice_de_carga: 86,
      presion_maxima: 44,
      indice_velocidad: 190,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 1650.0,
      precio_mayoreo: 1520.0,
      precio_coste: 1200.0,
      descripcion: "Llanta económica para autos compactos",
      id_marca: 4,
      id_categoria: 1,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Continental 205/55R16",
      lonas: 4,
      rin: 16,
      ancho_rin: 205,
      alto_rin: 55,
      version: "ContiPremiumContact 6",
      profundidad: 9,
      indice_de_carga: 91,
      presion_maxima: 44,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 2700.0,
      precio_mayoreo: 2500.0,
      precio_coste: 1950.0,
      descripcion: "Turismo confort y bajo ruido",
      id_marca: 4,
      id_categoria: 1,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Continental 235/60R17",
      lonas: 6,
      rin: 17,
      ancho_rin: 235,
      alto_rin: 60,
      version: "CrossContact LX2",
      profundidad: 10,
      indice_de_carga: 102,
      presion_maxima: 50,
      indice_velocidad: 200,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 3900.0,
      precio_mayoreo: 3600.0,
      precio_coste: 2800.0,
      descripcion: "SUV y crossover todo tiempo",
      id_marca: 4,
      id_categoria: 2,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Continental 255/55R19",
      lonas: 6,
      rin: 19,
      ancho_rin: 255,
      alto_rin: 55,
      version: "PremiumContact 6",
      profundidad: 10,
      indice_de_carga: 105,
      presion_maxima: 50,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 6200.0,
      precio_mayoreo: 5800.0,
      precio_coste: 4500.0,
      descripcion: "Premium SUV y pickup",
      id_marca: 4,
      id_categoria: 2,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Michelin 225/50R17",
      lonas: 4,
      rin: 17,
      ancho_rin: 225,
      alto_rin: 50,
      version: "Pilot Sport 4",
      profundidad: 9,
      indice_de_carga: 94,
      presion_maxima: 44,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 3200.0,
      precio_mayoreo: 2980.0,
      precio_coste: 2400.0,
      descripcion: "Turismo deportivo",
      id_marca: 1,
      id_categoria: 1,
      id_diseno: 6,
    },
    {
      nombre: "Llanta Bridgestone 235/65R17",
      lonas: 6,
      rin: 17,
      ancho_rin: 235,
      alto_rin: 65,
      version: "Dueler H/L 400",
      profundidad: 10,
      indice_de_carga: 104,
      presion_maxima: 50,
      indice_velocidad: 200,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 4100.0,
      precio_mayoreo: 3800.0,
      precio_coste: 3000.0,
      descripcion: "SUV familiar todo tiempo",
      id_marca: 2,
      id_categoria: 2,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Goodyear 205/60R16",
      lonas: 4,
      rin: 16,
      ancho_rin: 205,
      alto_rin: 60,
      version: "Assurance TripleMax 2",
      profundidad: 8,
      indice_de_carga: 92,
      presion_maxima: 44,
      indice_velocidad: 200,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 2400.0,
      precio_mayoreo: 2220.0,
      precio_coste: 1750.0,
      descripcion: "Sedán mediano confort",
      id_marca: 3,
      id_categoria: 1,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Continental 195/55R16",
      lonas: 4,
      rin: 16,
      ancho_rin: 195,
      alto_rin: 55,
      version: "EcoContact 6",
      profundidad: 8,
      indice_de_carga: 87,
      presion_maxima: 44,
      indice_velocidad: 200,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 1980.0,
      precio_mayoreo: 1820.0,
      precio_coste: 1450.0,
      descripcion: "Compacto económico",
      id_marca: 4,
      id_categoria: 1,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Michelin 245/70R17",
      lonas: 6,
      rin: 17,
      ancho_rin: 245,
      alto_rin: 70,
      version: "LTX Trail",
      profundidad: 11,
      indice_de_carga: 113,
      presion_maxima: 50,
      indice_velocidad: 180,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 5300.0,
      precio_mayoreo: 4950.0,
      precio_coste: 3850.0,
      descripcion: "Pickup y 4x4 todoterreno",
      id_marca: 1,
      id_categoria: 2,
      id_diseno: 4,
    },
    {
      nombre: "Llanta Bridgestone 185/70R14",
      lonas: 4,
      rin: 14,
      ancho_rin: 185,
      alto_rin: 70,
      version: "Ecopia EP150",
      profundidad: 8,
      indice_de_carga: 88,
      presion_maxima: 44,
      indice_velocidad: 190,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 1580.0,
      precio_mayoreo: 1460.0,
      precio_coste: 1150.0,
      descripcion: "Auto compacto ciudad",
      id_marca: 2,
      id_categoria: 1,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Goodyear 255/70R18",
      lonas: 6,
      rin: 18,
      ancho_rin: 255,
      alto_rin: 70,
      version: "Wrangler Duratrac",
      profundidad: 11,
      indice_de_carga: 113,
      presion_maxima: 50,
      indice_velocidad: 180,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 5900.0,
      precio_mayoreo: 5500.0,
      precio_coste: 4300.0,
      descripcion: "Camioneta y SUV grande",
      id_marca: 3,
      id_categoria: 2,
      id_diseno: 5,
    },
    {
      nombre: "Llanta Continental 225/65R17",
      lonas: 6,
      rin: 17,
      ancho_rin: 225,
      alto_rin: 65,
      version: "CrossContact",
      profundidad: 10,
      indice_de_carga: 102,
      presion_maxima: 50,
      indice_velocidad: 200,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 3600.0,
      precio_mayoreo: 3350.0,
      precio_coste: 2600.0,
      descripcion: "SUV crossover versátil",
      id_marca: 4,
      id_categoria: 2,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Michelin 215/55R17",
      lonas: 4,
      rin: 17,
      ancho_rin: 215,
      alto_rin: 55,
      version: "Primacy 4",
      profundidad: 9,
      indice_de_carga: 94,
      presion_maxima: 44,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 2900.0,
      precio_mayoreo: 2680.0,
      precio_coste: 2100.0,
      descripcion: "Sedán y compacto premium",
      id_marca: 1,
      id_categoria: 1,
      id_diseno: 2,
    },
    {
      nombre: "Llanta Bridgestone 265/60R18",
      lonas: 6,
      rin: 18,
      ancho_rin: 265,
      alto_rin: 60,
      version: "Dueler H/T 684",
      profundidad: 10,
      indice_de_carga: 110,
      presion_maxima: 50,
      indice_velocidad: 200,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 4700.0,
      precio_mayoreo: 4380.0,
      precio_coste: 3400.0,
      descripcion: "SUV y pickup alto rendimiento",
      id_marca: 2,
      id_categoria: 2,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Goodyear 235/55R18",
      lonas: 6,
      rin: 18,
      ancho_rin: 235,
      alto_rin: 55,
      version: "Eagle F1 Asymmetric",
      profundidad: 10,
      indice_de_carga: 99,
      presion_maxima: 50,
      indice_velocidad: 210,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 4400.0,
      precio_mayoreo: 4100.0,
      precio_coste: 3200.0,
      descripcion: "SUV deportivo",
      id_marca: 3,
      id_categoria: 2,
      id_diseno: 3,
    },
    {
      nombre: "Llanta Continental 245/70R16",
      lonas: 6,
      rin: 16,
      ancho_rin: 245,
      alto_rin: 70,
      version: "TerrainContact A/T",
      profundidad: 11,
      indice_de_carga: 111,
      presion_maxima: 50,
      indice_velocidad: 180,
      imagen_3d: "/Modelo3d/camaro_copo_tyre/scene.gltf",
      precio_detalle: 4000.0,
      precio_mayoreo: 3720.0,
      precio_coste: 2900.0,
      descripcion: "Camioneta pesada y trabajo",
      id_marca: 4,
      id_categoria: 3,
      id_diseno: 4,
    },
  ];

  for (const producto of productos) {
    await prisma.producto.create({
      data: producto,
    });
  }

  console.log("Productos insertados");
}

module.exports = { insertProductos };
